### ISSUE TITLE
address domain regular sample doubt

### ISSUE THREAD

**Issue by Fred0715** [cuckoohello/dnsmasq-regex#1]
when I read this document, I don't find sample of address regular.

Finally, I find result in the following link:
http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2013q2/007124.html

for example:
address=/:myvpn[0-9]*.company.com:/192.168.1.15

It works

**Comment by cuckoohello** [comment]
Ipset supports regex too with the same structure.

You can also use `address=/:^myvpn[0-9]*.company.com$:/192.168.1.15` for more accurate regex.

**Comment by daluu** [comment]
Does it support regex for server too? Or does that require https://github.com/lixingcong/dnsmasq-regex?

**Comment by cuckoohello** [comment]
Yes


ipset=/:^avatars[0-9]{1}\.githubusercontent\.com$:/vpn


server=/:^avatars[0-9]{1}\.githubusercontent\.com$:/208.67.222.222#5353

https://github.com/cuckoohello/gfwlist/blob/master/gfw.conf#L155
[https://avatars3.githubusercontent.com/u/869245?s=400&v=4]<https://github.com/cuckoohello/gfwlist/blob/master/gfw.conf#L155>

cuckoohello/gfwlist<https://github.com/cuckoohello/gfwlist/blob/master/gfw.conf#L155>
github.com
Contribute to gfwlist development by creating an account on Github.




________________________________
发件人: David Luu <notifications@github.com>
发送时间: 2018年8月10日 7:04
收件人: cuckoohello/dnsmasq-regex
抄送: Yafeng Shan; State change
主题: Re: [cuckoohello/dnsmasq-regex] address domain regular sample doubt (#1)


Does it support regex for server too? Or does that require https://github.com/lixingcong/dnsmasq-regex?

GitHub - lixingcong/dnsmasq-regex: dnsmasq with regex ...<https://github.com/lixingcong/dnsmasq-regex>
github.com
dnsmasq with regex support. Lastest version: 2.80test3. patches: 001-regex-server.patch; 002-regex-ipset.patch; Inspired by these repos: dnsmasq-regexp_2.76



―
